services:
  - type: web
    name: kaching-bundles-backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    plan: starter
    autoDeploy: true
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        value: <YOUR_MONGODB_CONNECTION_STRING>
      - key: SHOPIFY_API_KEY
        value: <YOUR_SHOPIFY_API_KEY>
      - key: SHOPIFY_API_SECRET
        value: <YOUR_SHOPIFY_API_SECRET>
      - key: SCOPES
        value: read_products,write_products
      - key: HOST
        value: https://kaching-bundles-backend.onrender.com
